# Generated by Django 2.2.7 on 2020-01-24 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='funds',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
