# Generated by Django 3.0.1 on 2020-01-14 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(default='test', max_length=100)),
                ('lastname', models.CharField(default='test', max_length=100)),
                ('username', models.CharField(default='test', max_length=100)),
                ('email', models.EmailField(default='test@gmail.com', max_length=100)),
                ('password', models.CharField(default='test', max_length=100)),
                ('phone', models.CharField(default='test', max_length=100)),
                ('cv', models.FileField(default='templates/base.html', upload_to='cv')),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
