# Generated by Django 2.2.7 on 2020-01-10 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200110_1627'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_description',
            new_name='user_cv',
        ),
    ]
