# Generated by Django 3.0.1 on 2020-01-14 11:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0003_appuser_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='email',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='password',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='username',
        ),
        migrations.AlterField(
            model_name='appuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
