# Generated by Django 3.0.1 on 2020-01-14 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20200114_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='cv',
            field=models.FileField(upload_to='cv'),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='phone',
            field=models.CharField(max_length=100),
        ),
    ]
