# Generated by Django 2.2.7 on 2020-01-22 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20200114_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='cv',
            field=models.FileField(null=True, upload_to='cv'),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
