# Generated by Django 2.2.7 on 2020-01-10 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20200111_0532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
