# Generated by Django 2.2.7 on 2020-01-22 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20200122_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='cv'),
        ),
    ]
