# Generated by Django 2.2.7 on 2020-01-11 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20200111_0535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='cv',
        ),
    ]
