# Generated by Django 2.2.7 on 2020-01-11 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_remove_appuser_cv'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
