# Generated by Django 2.2.7 on 2020-01-11 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_appuser_cv'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appuser',
            old_name='cv',
            new_name='cv_upload',
        ),
    ]
