# Generated by Django 2.2.7 on 2020-01-11 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20200111_0959'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appuser',
            old_name='cv_upload',
            new_name='upload_cv',
        ),
    ]
