# Generated by Django 3.0.1 on 2020-01-13 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20200111_1022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='upload_cv',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='user',
        ),
        migrations.AddField(
            model_name='appuser',
            name='cv',
            field=models.FileField(default='templates/base.html', upload_to='cv'),
        ),
        migrations.AddField(
            model_name='appuser',
            name='email',
            field=models.EmailField(default='test@gmail.com', max_length=100),
        ),
        migrations.AddField(
            model_name='appuser',
            name='firstname',
            field=models.CharField(default='test', max_length=100),
        ),
        migrations.AddField(
            model_name='appuser',
            name='lastname',
            field=models.CharField(default='test', max_length=100),
        ),
        migrations.AddField(
            model_name='appuser',
            name='password',
            field=models.CharField(default='test', max_length=100),
        ),
        migrations.AddField(
            model_name='appuser',
            name='username',
            field=models.CharField(default='test', max_length=100),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='phone',
            field=models.CharField(default='test', max_length=100),
        ),
    ]
