# Generated by Django 2.2.7 on 2020-01-09 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_title', models.CharField(max_length=40)),
                ('message_time', models.DateTimeField(auto_now_add=True)),
                ('message_body', models.TextField()),
                ('user', models.ManyToManyField(to='user.User')),
            ],
        ),
    ]
