# Generated by Django 3.0.1 on 2020-01-27 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
        ('payment', '0006_auto_20200125_0636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='project',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='project.Project'),
        ),
    ]
