# Generated by Django 3.0.1 on 2020-02-05 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_auto_20200127_0734'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='project',
        ),
    ]
