# Generated by Django 3.0.2 on 2020-02-09 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='project_status',
            new_name='availability_status',
        ),
    ]
